### ISSUE TITLE
Add ESLint support

### ISSUE THREAD

**Issue by itaisteinherz** [itaisteinherz/neo4j-console#15]

**Comment by robinnorth** [comment]
Do you plan to use a task runner like Gulp or Grunt at all in this project? If so, there are ESLint plugins for both frameworks that will allow you to create a lint task. Otherwise, using something like [mocha-eslint](https://github.com/BadgeLabs/mocha-eslint), linting could be run as part of the project's test script (defined in `package.json` and invoked with `npm test`).

**Comment by ajzawawi** [comment]
@itaisteinherz Please let us know if you want to use a task runner, so we can configure eslint.

**Comment by ajzawawi** [comment]
@itaisteinherz Submitted eslint PR. Please review.
