### ISSUE TITLE
What are the benefits of using a task runner like Gulp or Grunt?

### ISSUE THREAD

**Issue by itaisteinherz** [itaisteinherz/neo4j-console#22]
@robinnorth

**Comment by ajzawawi** [comment]
@itaisteinherz  You can lint, minify, uglify, concat, run your test suite, setup continuous integration, add documentation with JSdoc, etc with one command. @robinnorth What do you have in mind, Gulp, Grunt or Webpack?

**Comment by beforan** [comment]
It's definitely the convenience as @ajzawawi says, of performing many tasks with one command.

It's also ensuring that anyone building uses the same process. You could tell people that to use your source they have to build SASS, minify your JS, and that they should run tests, but they might run the tools in different orders, with different flags, they might not know how to do some of them, and they might ignore recommendations.

With a task runner, you make their life easier, you know that everyone's running the same tools and command lines, and even better, exactly what commands are run is documented, in your task runner file! So anyone working with the codebase can see the process.

**Comment by robinnorth** [comment]
@itaisteinherz, @ajzawawi and @beforan have both provided a good outline of why you might want to use a task runner. @beforan in particular hit the nail on the head -- it's all about convenience and consistency.

I've used both Grunt and gulp in my projects (typically web apps or JS libs) to help with development and building releases. These projects generally have uncompiled source files located in a `src` directory and build releases into a `dist` directory for deployment to production/consumption by other libraries.

For example, I have a 'server' task that fires up a local web server (using Connect or, more recently, Browsersync) to serve files from my `src` directory and watch them for changes, allowing hot-reloading of files after any compilation tasks have been completed (e.g. compiling SASS into CSS, transpiling ES6 code with Babel etc.). I have a 'build' task that can then be run to lint and compile my source files into a releaseable build, and, finally, a 'release' task that bumps the project's version number everywhere it's listed (npm and Bower package manifests, in banner comments etc.), runs the 'build' task and then cuts a git-flow release.

In your project's case, a task runner could be used to provide a single command to fire up the app and then hot-reload the server on source file changes, potentially with code linting being triggered on any change. A 'release' task might also be of use to you.

As for preference for a choice of task runner, I've always found Grunt to be very easy to use and configure. It also has the largest ecosystem of plugins. However, I've recently switched to gulp because its stream-based nature makes it a lot faster than Grunt when iterating over large projects. You have to write more code to configure tasks, which makes it a bit slower to set up initially, but arguably more node-y, as you're not restricted to using gulp plugins. I have yet to fully delve into Webpack as it's always seemed overly complex for my needs, but YMMV.

**Comment by pmcbride446** [comment]
@itaisteinherz As mentioned previously, one of the really useful things about using a build tool is that anyone working on a project will have a predefined system in place for compiling assets etc. Coupling a build system with a solid `readme.md` can make a huge difference in OS software as i lowers the barrier of entry.
